### ISSUE TITLE
Plural - 1 Confirmations

### ISSUE THREAD

**Issue by klauslovgreen** [blockchain/Blockchain-Translations#83]
The blue status box shows up as "1 Confirmations" on the Bitcoin Address pages

![screen shot 2014-11-19 at 20 15 40](https://cloud.githubusercontent.com/assets/9731754/5112686/b49860c8-7029-11e4-8e4a-74374bcf4f75.png)

**Comment by tuzzolo** [comment]
Thanks. Have added this to our internal
